package com.mycompany.consumoapiventanamdi.mdi;

import com.mycompany.consumoapiventanamdi.subventanas.VentanaPosts;

public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp_inicio = new javax.swing.JDesktopPane();
        mb_inicio = new javax.swing.JMenuBar();
        jm_cargar_post = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dp_inicioLayout = new javax.swing.GroupLayout(dp_inicio);
        dp_inicio.setLayout(dp_inicioLayout);
        dp_inicioLayout.setHorizontalGroup(
            dp_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        dp_inicioLayout.setVerticalGroup(
            dp_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        jm_cargar_post.setText("Cargar Posts");
        jm_cargar_post.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_cargar_postMouseClicked(evt);
            }
        });
        mb_inicio.add(jm_cargar_post);

        setJMenuBar(mb_inicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp_inicio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp_inicio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_cargar_postMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_cargar_postMouseClicked
        // Instanciamos la ventana interna
        VentanaPosts ventanaPosts = new VentanaPosts();
        // Agregamos la ventana interna
        dp_inicio.add(ventanaPosts);
        // Hacemos visible la sub-ventana
        ventanaPosts.setVisible(true);
    }//GEN-LAST:event_jm_cargar_postMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dp_inicio;
    private javax.swing.JMenu jm_cargar_post;
    private javax.swing.JMenuBar mb_inicio;
    // End of variables declaration//GEN-END:variables
}
