package com.mycompany.consumoapiventanamdi.subventanas;

import com.mycompany.consumoapiventanamdi.model.Post;
import com.mycompany.consumoapiventanamdi.utils.ConexionAPI;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class VentanaPosts extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaPosts
     */
    public VentanaPosts() {
        initComponents();
        cargarDatosEnTabla();
    }

    private void cargarDatosEnTabla() {
        // Instanciamos nuestra clase de conexión
        ConexionAPI api = new ConexionAPI();

        // Obtenemos la lista de posts
        List<Post> posts = api.obtenerPosts();

        // Obtenemos el modelo de la tabla que creaste en la interfaz visual
        // Reemplaza "jt_tabla" por el nombre de variable que tenga tu tabla
        DefaultTableModel modelo = (DefaultTableModel) jt_tabla.getModel();

        // Limpiamos la tabla por si ya tenía datos previos
        modelo.setRowCount(0);

        // Iteramos sobre la lista y agregamos las filas
        for (Post post : posts) {
            Object[] fila = new Object[4];
            fila[0] = post.getUserId();
            fila[1] = post.getId();
            fila[2] = post.getTitle();
            fila[3] = post.getBody();

            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_tabla = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listado de Posts");

        jScrollPane1.setBorder(null);

        jt_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User ID", "ID", "Titulo", "Body"
            }
        ));
        jScrollPane1.setViewportView(jt_tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_tabla;
    // End of variables declaration//GEN-END:variables
}
